name: inpulse_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "assets/icons/logo.png"
  adaptive_icon_foreground: "assets/icons/logo.png"
  remove_alpha_ios: true
  ios: false
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#22252A"
  image: assets/icons/inpulse_logo.png
  android_12:
    color: "#22252A"
    icon_background_color: "#22252A"
    image: assets/icons/inpulse_logo.png