name: inpulse_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900


flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "assets/icons/logo.png"
  adaptive_icon_foreground: "assets/icons/logo.png"
  remove_alpha_ios: true
  ios: false
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21


flutter_native_splash:
  color: "#22252A"
  image: assets/icons/inpulse_full_logo.png
  fullscreen: true

  android_gravity: center
  ios_content_mode: scaleAspectFit

  android_12:
    color: "#22252A"
    image: assets/icons/inpulse_full_logo.png
    icon_background_color: "#22252A"

